2 1 model
thinknetica-django-lab-02/i10dev pull request #26
Opened 2021-03-31 19:37 UTC by i10dev

Closes #4

2021-04-01 11:05 UTC, mikhailborodin requested changes

2021-04-01 11:05 UTC, mikhailborodin commented on clone_ozon/main/models.py
> +    # category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
почему они закомментированы?

2021-04-03 20:37 UTC, mikhailborodin commented on clone_ozon/main/models.py
> +    # category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
у товара должна быть категория

2021-04-05 16:27 UTC, i10dev reviewed
Обновленно

2021-04-06 12:07 UTC, mikhailborodin approved these changes

2021-04-06 15:27 UTC, closed without merging